import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createInterface } from "node:readline/promises";
import type { Command } from "commander";
import type { CliContext } from "../index";
import { printErr, printLine } from "../util/output";

/**
 * `strand init` — first-run wizard. Picks an LLM provider, stores the API
 * key, and writes a minimal `.env` in cwd (if none exists). Non-destructive:
 * refuses to overwrite an existing .env unless `--force` is passed.
 */

const PROVIDERS = [
  { id: "anthropic", key: "ANTHROPIC_API_KEY", model: "claude-opus-4-7" },
  { id: "openai", key: "OPENAI_API_KEY", model: "gpt-5" },
  { id: "xai", key: "XAI_API_KEY", model: "grok-4.20-reasoning" },
  { id: "gemini", key: "GEMINI_API_KEY", model: "gemini-2.5-pro" },
] as const;

type ProviderId = (typeof PROVIDERS)[number]["id"];

export function registerInitCmd(program: Command, _ctx: CliContext): void {
  program
    .command("init")
    .description("first-run wizard — pick an LLM provider, store the key, write .env")
    .option("--force", "overwrite an existing .env")
    .option("--provider <id>", "pick provider non-interactively (anthropic|openai|xai|gemini)")
    .option("--store <name>", "credential store (env|file|encrypted-file|keychain)", "env")
    .action(async (opts: { force?: boolean; provider?: ProviderId; store: string }) => {
      const rl = createInterface({ input: process.stdin, output: process.stdout });
      try {
        printLine("strand init — first-run setup");
        printLine("");

        const providerId =
          opts.provider ??
          ((await ask(rl, "provider [anthropic/openai/xai/gemini] (anthropic): ")).trim() ||
            "anthropic");
        const provider = PROVIDERS.find((p) => p.id === providerId);
        if (!provider) {
          printErr(`unknown provider "${providerId}". Expected: anthropic|openai|xai|gemini`);
          process.exit(1);
        }

        const key = await ask(rl, `${provider.key} (input hidden is NOT supported here — paste): `);
        if (!key.trim()) {
          printErr(`${provider.key} is required`);
          process.exit(1);
        }

        const storeName = opts.store;
        if (!["env", "file", "encrypted-file", "keychain"].includes(storeName)) {
          printErr(`unknown --store "${storeName}"`);
          process.exit(1);
        }

        // Write credential to the chosen store (except `env` — .env IS the store).
        if (storeName !== "env") {
          const auth = await import("@/auth");
          let store: { name: string; set(k: string, v: string): Promise<void> };
          switch (storeName) {
            case "file":
              store = new auth.FileCredentialStore();
              break;
            case "encrypted-file":
              store = new auth.EncryptedFileCredentialStore();
              break;
            case "keychain":
              store = new auth.KeychainCredentialStore();
              break;
            default:
              printErr(`unreachable: ${storeName}`);
              process.exit(1);
          }
          await store.set(provider.key, key.trim());
          printLine(`✓ ${provider.key} → ${store.name}`);
        }

        // Always (re)write `.env` with LLM_PROVIDER + credential store selection. For
        // `env` store, also write the key. Other stores don't need it in .env.
        const envPath = join(process.cwd(), ".env");
        if (existsSync(envPath) && !opts.force) {
          printErr(`.env already exists at ${envPath} — re-run with --force to overwrite.`);
          printLine("");
          printLine("To continue without overwriting, add these lines manually:");
          printLine(`  LLM_PROVIDER=${provider.id}`);
          printLine(`  STRAND_CREDENTIAL_STORE=${storeName}`);
          if (storeName === "env") printLine(`  ${provider.key}=${key.trim()}`);
          process.exit(0);
        }

        const lines = [
          "# strand .env — generated by `strand init`",
          `LLM_PROVIDER=${provider.id}`,
          `LLM_MODEL_REASONER=${provider.model}`,
          `STRAND_CREDENTIAL_STORE=${storeName}`,
          ...(storeName === "env" ? [`${provider.key}=${key.trim()}`] : []),
          "",
        ];
        writeFileSync(envPath, `${lines.join("\n")}`, { mode: 0o600 });
        printLine(`✓ wrote ${envPath}`);
        printLine("");
        printLine("Next:");
        printLine("  strand doctor                 # verify everything resolves");
        printLine('  strand run "your goal here"   # fire the plan runner');
      } finally {
        rl.close();
      }
    });
}

async function ask(rl: ReturnType<typeof createInterface>, prompt: string): Promise<string> {
  return rl.question(prompt);
}
